# zeelos - connect-clusters
# MAINTAINER zeelos.io - https://zeelos.io

version: '3.6'

services:

  kafka-connect-influxdb:
    image: zeelos/kafka-connect-leshan-influxdb:0.1-SNAPSHOT
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka-cloud:9092
      - CONNECT_LISTENERS=https://0.0.0.0:8083
      - CONNECT_GROUP_ID=zeelos-connect-${GATEWAY_ID}-influxdb-group
      - CONNECT_CONFIG_STORAGE_TOPIC=zeelos-connect-${GATEWAY_ID}-influxdb-configs
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_TOPIC=zeelos-connect-${GATEWAY_ID}-influxdb-offsets
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_FLUSH_INTERVAL_MS=10000
      - CONNECT_STATUS_STORAGE_TOPIC=zeelos-connect-${GATEWAY_ID}-influxdb-status
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=https://schema-registry-cloud:8083
      - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_VALUE_CONVERTER_ENHANCED_AVRO_SCHEMA_SUPPORT=true
      - CONNECT_VALUE_CONVERTER_CONNECT_META_DATA=false
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=https://schema-registry-cloud:8083
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka-connect-influxdb
      - CONNECT_REST_ADVERTISED_PORT=8083
      - CONNECT_REST_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CONNECT_REST_ACCESS_CONTROL_ALLOW_ORIGIN=*
      - CONNECT_ZOOKEEPER_CONNECT=zookeeper-cloud:2181
      - CONNECT_LOG4J_ROOT_LOGLEVEL=INFO
      - CONNECT_LOG4J_LOGGERS=com.datamountaineer=DEBUG
      - CONNECT_PLUGIN_PATH=/opt/connectors
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_PORT=9584
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
      - CONNECT_SECURITY_PROTOCOL=SSL
      - CONNECT_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - CONNECT_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONNECT_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - CONNECT_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONNECT_SSL_CLIENT_AUTH=true
      - CONNECT_PRODUCER_SECURITY_PROTOCOL=SSL
      - CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONNECT_PRODUCER_SSL_KEY_PASSWORD=itsasecret
      - CONNECT_CONSUMER_SECURITY_PROTOCOL=SSL
      - CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - CONNECT_CONSUMER_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONNECT_CONSUMER_SSL_KEY_PASSWORD=itsasecret
      - KAFKA_OPTS=-Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
                   -Djavax.net.ssl.trustStorePassword=itsasecret
                   -Djavax.net.ssl.keyStore=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
                   -Djavax.net.ssl.keyStorePassword=itsasecret
      - SCHEMA_REGISTRY_OPTS=-Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
                             -Djavax.net.ssl.trustStorePassword=itsasecret
                             -Djavax.net.ssl.keyStore=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
                             -Djavax.net.ssl.keyStorePassword=itsasecret
    secrets:
      - source: kafka.connect-cloud.keystore.jks
        target: /etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - source: kafka.connect-cloud.truststore.jks
        target: /etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - source: client-cloud.certificate.pem
        target: /etc/kafka/secrets/client-cloud.certificate.pem
      - source: client-cloud.key
        target: /etc/kafka/secrets/client-cloud.key
    networks:
      - cloudnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == cloud
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Connect - Your hub for connecting Apache Kafka to all your systems"
      io.zeelos.gatewayId: ${GATEWAY_ID}

  kafka-connect-leshan-asset:
    image: zeelos/kafka-connect-leshan-influxdb:0.1-SNAPSHOT
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka-cloud:9092
      - CONNECT_LISTENERS=https://0.0.0.0:8083
      - CONNECT_GROUP_ID=zeelos-connect-${GATEWAY_ID}-leshan-asset-group
      - CONNECT_CONFIG_STORAGE_TOPIC=zeelos-connect-${GATEWAY_ID}-leshan-asset-configs
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_TOPIC=zeelos-connect-${GATEWAY_ID}-leshan-asset-offsets
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_FLUSH_INTERVAL_MS=10000
      - CONNECT_STATUS_STORAGE_TOPIC=zeelos-connect-${GATEWAY_ID}-leshan-asset-status
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=https://schema-registry-cloud:8083
      - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_VALUE_CONVERTER_ENHANCED_AVRO_SCHEMA_SUPPORT=true
      - CONNECT_VALUE_CONVERTER_CONNECT_META_DATA=false
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=https://schema-registry-cloud:8083
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka-connect-leshan-asset
      - CONNECT_REST_ADVERTISED_PORT=8083
      - CONNECT_REST_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CONNECT_REST_ACCESS_CONTROL_ALLOW_ORIGIN=*
      - CONNECT_ZOOKEEPER_CONNECT=zookeeper-cloud:2181
      - CONNECT_LOG4J_ROOT_LOGLEVEL=INFO
      - CONNECT_LOG4J_LOGGERS=io.zeelos.leshan=DEBUG
      - CONNECT_PLUGIN_PATH=/opt/connectors
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_PORT=9585
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
      - CONNECT_SECURITY_PROTOCOL=SSL
      - CONNECT_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - CONNECT_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONNECT_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - CONNECT_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONNECT_SSL_CLIENT_AUTH=true
      - CONNECT_PRODUCER_SECURITY_PROTOCOL=SSL
      - CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONNECT_PRODUCER_SSL_KEY_PASSWORD=itsasecret
      - CONNECT_CONSUMER_SECURITY_PROTOCOL=SSL
      - CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - CONNECT_CONSUMER_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONNECT_CONSUMER_SSL_KEY_PASSWORD=itsasecret
      - KAFKA_OPTS=-Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
                   -Djavax.net.ssl.trustStorePassword=itsasecret
                   -Djavax.net.ssl.keyStore=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
                   -Djavax.net.ssl.keyStorePassword=itsasecret
      - SCHEMA_REGISTRY_OPTS=-Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.connect-cloud.truststore.jks
                             -Djavax.net.ssl.trustStorePassword=itsasecret
                             -Djavax.net.ssl.keyStore=/etc/kafka/secrets/kafka.connect-cloud.keystore.jks
                             -Djavax.net.ssl.keyStorePassword=itsasecret
    secrets:
      - source: kafka.connect-cloud.keystore.jks
        target: /etc/kafka/secrets/kafka.connect-cloud.keystore.jks
      - source: kafka.connect-cloud.truststore.jks
        target: /etc/kafka/secrets/kafka.connect-cloud.truststore.jks
      - source: client-cloud.certificate.pem
        target: /etc/kafka/secrets/client-cloud.certificate.pem
      - source: client-cloud.key
        target: /etc/kafka/secrets/client-cloud.key
    networks:
      - cloudnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == cloud
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Connect - Your hub for connecting Apache Kafka to all your systems"
      io.zeelos.gatewayId: ${GATEWAY_ID}

secrets:
  kafka.connect-cloud.keystore.jks:
    file: ./security/kafka.connect-cloud.keystore.jks
  kafka.connect-cloud.truststore.jks:
    file: ./security/kafka.connect-cloud.truststore.jks
  client-cloud.certificate.pem:
    file: ./security/client-cloud.certificate.pem
  client-cloud.key:
    file: ./security/client-cloud.key


networks:
  cloudnet:
    external: true
    name: cloudnet