# zeelos - mirromaker
# MAINTAINER zeelos.io - https://zeelos.io

version: '3.6'

services:

  kafka-mirrormaker:
    image: zeelos/kafka-mirrormaker:4.1.1
    environment:
      - MIRRORMAKER_WHITE_LIST=^iot.${GATEWAY_ID}.((?!req).)*$$
      - MIRRORMAKER_ABORT_ON_SEND_FAILURE=true
      - MIRRORMAKER_OFFSET_COMMIT_INTERVAL_MS=60000
      - MIRRORMAKER_NUM_STREAMS=1
      - CONSUMER_BOOTSTRAP_SERVERS=kafka-gateway:9082
      - CONSUMER_GROUP_ID=mirrormaker_cloud_${GATEWAY_ID}
      - CONSUMER_AUTO_OFFSET_RESET=earliest
      - PRODUCER_BOOTSTRAP_SERVERS=kafka-cloud:9092
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_PORT=9574
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
      - PRODUCER_SECURITY_PROTOCOL=SSL
      - PRODUCER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - PRODUCER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - PRODUCER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - PRODUCER_SSL_KEYSTORE_PASSWORD=itsasecret
      - PRODUCER_SSL_KEY_PASSWORD=itsasecret
      - CONSUMER_SECURITY_PROTOCOL=SSL
      - CONSUMER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-gateway.truststore.jks
      - CONSUMER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONSUMER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-gateway.keystore.jks
      - CONSUMER_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONSUMER_SSL_KEY_PASSWORD=itsasecret
    secrets:
      - source: kafka.client-cloud.keystore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - source: kafka.client-cloud.truststore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - source: kafka.client-gateway.keystore.jks
        target: /etc/kafka/secrets/kafka.client-gateway.keystore.jks
      - source: kafka.client-gateway.truststore.jks
        target: /etc/kafka/secrets/kafka.client-gateway.truststore.jks
      - source: client_security_cloud.properties
        target: /etc/kafka/secrets/client_security_cloud.properties
      - source: client_security_gateway.properties
        target: /etc/kafka/secrets/client_security_gateway.properties
    networks:
      - cloudnet
      - gateway
    # ports:
    #   - 9574:9574
    deploy:
      placement:
        constraints:
          - node.labels.type == cloud
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Kafka MirrorMaker - A stand-alone tool for copying data between two Apache Kafka clusters"
      io.zeelos.gatewayId: ${GATEWAY_ID}

secrets:
  kafka.client-cloud.keystore.jks:
    file: ./security/kafka.client-cloud.keystore.jks
  kafka.client-cloud.truststore.jks:
    file: ./security/kafka.client-cloud.truststore.jks
  kafka.client-gateway.keystore.jks:
    file: ./security/kafka.client-gateway.keystore.jks
  kafka.client-gateway.truststore.jks:
    file: ./security/kafka.client-gateway.truststore.jks
  client_security_cloud.properties:
    file: ./security/client_security_cloud.properties
  client_security_gateway.properties:
    file: ./security/client_security_gateway.properties

networks:
  cloudnet:
    external: true
    name: cloudnet
  gateway:
    external: true
    name: edgenet_${GATEWAY_ID}