# zeelos - edge
# MAINTAINER zeelos.io - https://zeelos.io

version: '3.1'

services:

  zookeeper-edge:
    image: confluentinc/cp-zookeeper:4.1.0
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2171
      - ZOOKEEPER_TICK_TIME=2000
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_PORT=9575
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
    networks:
      - edgenet
      - cloudnet
    ports:
      - 2171:2171
      - 9575:9575
    deploy:
      placement:
        constraints:
          - node.labels.type == server1
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "ZooKeeper - An open-source server which enables highly reliable distributed coordination"

  kafka-edge:
    image: confluentinc/cp-kafka:4.1.0
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-edge:2171
      - KAFKA_ADVERTISED_LISTENERS=SSL://kafka-edge:9082
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms512M
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_PORT=9571
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
      - KAFKA_INTER_BROKER_LISTENER_NAME=SSL
      - KAFKA_SSL_KEYSTORE_FILENAME=kafka.kafka-edge.keystore.jks
      - KAFKA_SSL_KEYSTORE_CREDENTIALS=kafka-edge_keystore_creds
      - KAFKA_SSL_KEY_CREDENTIALS=kafka-edge_sslkey_creds
      - KAFKA_SSL_TRUSTSTORE_FILENAME=kafka.kafka-edge.truststore.jks
      - KAFKA_SSL_TRUSTSTORE_CREDENTIALS=kafka-edge_truststore_creds
      - KAFKA_SSL_CLIENT_AUTH=required
      - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:HTTPS
    secrets:
      - source: kafka.kafka-edge.keystore.jks
        target: /etc/kafka/secrets/kafka.kafka-edge.keystore.jks
      - source: kafka-edge_keystore_creds
        target: /etc/kafka/secrets/kafka-edge_keystore_creds
      - source: kafka-edge_sslkey_creds
        target: /etc/kafka/secrets/kafka-edge_sslkey_creds
      - source: kafka.kafka-edge.truststore.jks
        target: /etc/kafka/secrets/kafka.kafka-edge.truststore.jks
      - source: kafka-edge_truststore_creds
        target: /etc/kafka/secrets/kafka-edge_truststore_creds
    networks:
      - edgenet
      - cloudnet
    ports:
      - 9082:9082
      - 9571:9571
    deploy:
      placement:
        constraints:
          - node.labels.type == server1
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Kafka - A distributed streaming platform"

  schema-registry-edge:
    image: confluentinc/cp-schema-registry:4.1.0
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry-edge
      - SCHEMA_REGISTRY_LISTENERS=https://0.0.0.0:8071
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=SSL://kafka-cloud:9092
      - SCHEMA_REGISTRY_MASTER_ELIGIBILIY=false
      - SCHEMA_REGISTRY_ZK_NAMESPACE=zeelos
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN=*
      - SCHEMA_REGISTRY_JMX_HOSTNAME=localhost
      - SCHEMA_REGISTRY_JMX_PORT=9572
      - SCHEMA_REGISTRY_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                                 -Dcom.sun.management.jmxremote.ssl=false
      - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SSL
      - SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.schema-registry-edge.truststore.jks
      - SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.schema-registry-edge.keystore.jks
      - SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD=itsasecret
      - SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD=itsasecret
      - SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=HTTPS
      - SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.schema-registry-edge.truststore.jks
      - SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.schema-registry-edge.keystore.jks
      - SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=itsasecret
      - SCHEMA_REGISTRY_SSL_KEY_PASSWORD=itsasecret
      - SCHEMA_REGISTRY_SSL_CLIENT_AUTH=true
      - SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL=https
      - SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL=INFO
    secrets:
      - source: kafka.schema-registry-edge.keystore.jks
        target: /etc/kafka/secrets/kafka.schema-registry-edge.keystore.jks
      - source: kafka.schema-registry-edge.truststore.jks
        target: /etc/kafka/secrets/kafka.schema-registry-edge.truststore.jks
    networks:
      - edgenet
      - cloudnet
    ports:
      - 8071:8071
      - 9572:9572
    deploy:
      placement:
        constraints:
          - node.labels.type == server1
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Schema Registry - Schema registry for Apache Kafka"

  kafka-rest-edge:
    image: confluentinc/cp-kafka-rest:4.1.0
    environment:
      - KAFKA_REST_HOST_NAME=kafka-rest-edge
      - KAFKA_REST_LISTENERS=https://0.0.0.0:8072
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper-edge:2171
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka-edge:9082
      - KAFKA_REST_SCHEMA_REGISTRY_URL=https://schema-registry-edge:8071
      - KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN=*
      - KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS=30000
      - KAFKAREST_HEAP_OPTS=-Xmx64M -Xms64M
      - KAFKAREST_JMX_OPTS=-Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.local.only=false
                           -Dcom.sun.management.jmxremote.rmi.port=9573 -Dcom.sun.management.jmxremote.port=9573
                           -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                           -Dcom.sun.management.jmxremote.ssl=false
      - KAFKA_REST_CLIENT_SECURITY_PROTOCOL=SSL
      - KAFKA_REST_CLIENT_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.rest-edge.truststore.jks
      - KAFKA_REST_CLIENT_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - KAFKA_REST_CLIENT_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.rest-edge.keystore.jks
      - KAFKA_REST_CLIENT_SSL_KEYSTORE_PASSWORD=itsasecret
      - KAFKA_REST_CLIENT_SSL_KEY_PASSWORD=itsasecret
      - KAFKA_REST_CLIENT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=HTTPS
      - KAFKA_REST_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.rest-edge.truststore.jks
      - KAFKA_REST_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - KAFKA_REST_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.rest-edge.keystore.jks
      - KAFKA_REST_SSL_KEYSTORE_PASSWORD=itsasecret
      - KAFKA_REST_SSL_KEY_PASSWORD=itsasecret
      - KAFKA_REST_SSL_CLIENT_AUTH=true
    secrets:
      - source: kafka.rest-edge.keystore.jks
        target: /etc/kafka/secrets/kafka.rest-edge.keystore.jks
      - source: kafka.rest-edge.truststore.jks
        target: /etc/kafka/secrets/kafka.rest-edge.truststore.jks
    networks:
      - edgenet
      - cloudnet
    ports:
      - 8072:8072
      - 9573:9573
    deploy:
      placement:
        constraints:
          - node.labels.type == server1
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Kafka REST Proxy - A RESTful interface to a Kafka cluster"

  kafka-mirrormaker:
    image: zeelos/kafka-mirrormaker:4.1.0
    environment:
      - MIRRORMAKER_WHITE_LIST=^server1_management_req
      - MIRRORMAKER_ABORT_ON_SEND_FAILURE=true
      - MIRRORMAKER_OFFSET_COMMIT_INTERVAL_MS=60000
      - MIRRORMAKER_NUM_STREAMS=1
      - CONSUMER_BOOTSTRAP_SERVERS=kafka-cloud:9092
      - CONSUMER_GROUP_ID=mirrormaker_server1
      - CONSUMER_AUTO_OFFSET_RESET=earliest
      - PRODUCER_BOOTSTRAP_SERVERS=kafka-edge:9082
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_PORT=9564
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
      - PRODUCER_SECURITY_PROTOCOL=SSL
      - PRODUCER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-edge.truststore.jks
      - PRODUCER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - PRODUCER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-edge.keystore.jks
      - PRODUCER_SSL_KEYSTORE_PASSWORD=itsasecret
      - PRODUCER_SSL_KEY_PASSWORD=itsasecret
      - CONSUMER_SECURITY_PROTOCOL=SSL
      - CONSUMER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - CONSUMER_SSL_TRUSTSTORE_PASSWORD=itsasecret
      - CONSUMER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - CONSUMER_SSL_KEYSTORE_PASSWORD=itsasecret
      - CONSUMER_SSL_KEY_PASSWORD=itsasecret
    secrets:
      - source: kafka.client-edge.keystore.jks
        target: /etc/kafka/secrets/kafka.client-edge.keystore.jks
      - source: kafka.client-edge.truststore.jks
        target: /etc/kafka/secrets/kafka.client-edge.truststore.jks
      - source: kafka.client-cloud.keystore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - source: kafka.client-cloud.truststore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - source: client_security_edge.properties
        target: /etc/kafka/secrets/client_security_edge.properties
      - source: client_security_cloud.properties
        target: /etc/kafka/secrets/client_security_cloud.properties
    networks:
      - edgenet
      - cloudnet
    ports:
      - 9564:9564
    deploy:
      placement:
        constraints:
          - node.labels.type == server1
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Kafka MirrorMaker - A stand-alone tool for copying data between two Apache Kafka clusters"

  leshan-server-kafka:
    image: zeelos/leshan-server-kafka:0.1-SNAPSHOT
    volumes:
      - leshan-server-data:/opt/leshan-server-kafka
    environment:
      - SERVERID=server1
      - KAFKA_BOOTSTRAP_SERVER=kafka-edge:9082
      - KAFKA_SCHEMA_REGISTRY_URL=https://schema-registry-edge:8071
      - JAVA_OPTS=-Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.local.only=false
                  -Dcom.sun.management.jmxremote.rmi.port=9590 -Dcom.sun.management.jmxremote.port=9590
                  -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                  -Dcom.sun.management.jmxremote.ssl=false -Xmx512M -Xms512M
                  -Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.client-edge.truststore.jks
                  -Djavax.net.ssl.trustStorePassword=itsasecret
                  -Djavax.net.ssl.keyStore=/etc/kafka/secrets/kafka.client-edge.keystore.jks
                  -Djavax.net.ssl.keyStorePassword=itsasecret
      - KAFKA_SSL_PROPERTIES_LOCATION=/etc/kafka/secrets/client_security_edge.properties
    secrets:
      - source: kafka.client-edge.keystore.jks
        target: /etc/kafka/secrets/kafka.client-edge.keystore.jks
      - source: kafka.client-edge.truststore.jks
        target: /etc/kafka/secrets/kafka.client-edge.truststore.jks
      - source: client_security_edge.properties
        target: /etc/kafka/secrets/client_security_edge.properties
    networks:
      - edgenet
    ports:
      - 5683:5683/udp
      - 5684:5684/udp
      - 8080:8080
      - 9590:9590
    deploy:
      placement:
        constraints:
          - node.labels.type == server1
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Leshan - OMA Lightweight M2M server and client in Java"

secrets:
  kafka.kafka-edge.keystore.jks:
    file: ./security/kafka.kafka-edge.keystore.jks
  kafka-edge_keystore_creds:
    file: ./security/kafka-edge_keystore_creds
  kafka-edge_sslkey_creds:
    file: ./security/kafka-edge_sslkey_creds
  kafka.kafka-edge.truststore.jks:
    file: ./security/kafka.kafka-edge.truststore.jks
  kafka-edge_truststore_creds:
    file: ./security/kafka-edge_truststore_creds
  kafka.schema-registry-edge.keystore.jks:
    file: ./security/kafka.schema-registry-edge.keystore.jks
  kafka.schema-registry-edge.truststore.jks:
    file: ./security/kafka.schema-registry-edge.truststore.jks
  kafka.rest-edge.keystore.jks:
    file: ./security/kafka.rest-edge.keystore.jks
  kafka.rest-edge.truststore.jks:
    file: ./security/kafka.rest-edge.truststore.jks
  kafka.client-edge.keystore.jks:
    file: ./security/kafka.client-edge.keystore.jks
  kafka.client-edge.truststore.jks:
    file: ./security/kafka.client-edge.truststore.jks
  client_security_edge.properties:
    file: ./security/client_security_edge.properties
  client_security_cloud.properties:
    file: ./security/client_security_cloud.properties

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
  leshan-server-data:

networks:
  edgenet:
    external:
      name: edgenet_server1
  cloudnet:
    external:
      name: cloudnet
