FROM karalabe/xgo-latest AS build
ARG VERSION=master

WORKDIR ${GOPATH}/src/github.com/danielqsj
RUN git clone --branch ${VERSION} https://github.com/danielqsj/kafka_exporter.git
WORKDIR ${GOPATH}/src/github.com/danielqsj/kafka_exporter
RUN xgo --targets=linux/386,linux/amd64,linux/arm-5,linux/arm-6,linux/arm-7,linux/arm64 .

FROM alpine

COPY --from=build /build /build
