global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prometheus-swarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor-cloud'
      type: 'A'
      port: 8080

  - job_name: 'cadvisor-edge'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor-edge'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter-cloud'
      type: 'A'
      port: 9100

  - job_name: 'node-exporter-edge'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter-edge'
      type: 'A'
      port: 9100

  - job_name: 'docker-exporter-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.docker-exporter-cloud'
      type: 'A'
      port: 9323

  - job_name: 'docker-exporter-edge'
    dns_sd_configs:
    - names:
      - 'tasks.docker-exporter-edge'
      type: 'A'
      port: 9323

  - job_name: 'zookeeper-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-cloud'
      type: 'A'
      port: 8080

  - job_name: 'zookeeper-edge'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-cloud'
      type: 'A'
      port: 8080

  - job_name: 'kafka-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-cloud'
      type: 'A'
      port: 8080

  - job_name: 'kafka-edge'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-edge'
      type: 'A'
      port: 8080

  - job_name: 'kafka-exporter-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-exporter-cloud'
      type: 'A'
      port: 8080

  - job_name: 'kafka-exporter-edge'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-exporter-edge'
      type: 'A'
      port: 8080

