global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prometheus-swarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'docker-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.docker-exporter'
      type: 'A'
      port: 9323

  - job_name: 'kafka-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-cloud'
      type: 'A'
      port: 8080

  - job_name: 'kafka-gateway1'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-gateway1'
      type: 'A'
      port: 8080

  - job_name: 'zookeeper-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.zookeeper-cloud'
      type: 'A'
      port: 8080

  - job_name: 'zookeeper-gateway1'
    dns_sd_configs:
    - names:
      - 'tasks.zookeeper-gateway1'
      type: 'A'
      port: 8080

  - job_name: 'kafka-exporter-cloud'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-exporter-cloud'
      type: 'A'
      port: 8080

  - job_name: 'kafka-exporter-gateway1'
    dns_sd_configs:
    - names:
      - 'tasks.kafka-exporter-gateway1'
      type: 'A'
      port: 8080

